In [26]:
import datetime, warnings, scipy 
import pandas as pd
import numpy as np
import math
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.externals import joblib

In [27]:
data = pd.read_csv('../data/data_testing_random_forest.csv')
data = data.dropna(axis=0, how='any')
y = data['ARRIVAL_DELAY_BIN_30']
X = data[['SCHEDULED_DEPARTURE','SCHEDULED_ARRIVAL', \
                  'AIRLINE_AS', 'AIRLINE_B6','AIRLINE_DL', 'AIRLINE_EV', 'AIRLINE_F9', 'AIRLINE_HA', 'AIRLINE_MQ', \
                  'AIRLINE_NK', 'AIRLINE_OO', 'AIRLINE_UA', 'AIRLINE_US', 'AIRLINE_VX','AIRLINE_WN',\
          'ORIGIN_WOE_30', 'DESTINATION_WOE_30', 'DAY_OF_YEAR_WOE_30']].copy()

display(X.head(5))
y = data.ARRIVAL_DELAY_BIN_30

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)
print(X_train.shape)

,SCHEDULED_DEPARTURE,SCHEDULED_ARRIVAL,AIRLINE_AS,AIRLINE_B6,AIRLINE_DL,AIRLINE_EV,AIRLINE_F9,AIRLINE_HA,AIRLINE_MQ,AIRLINE_NK,AIRLINE_OO,AIRLINE_UA,AIRLINE_US,AIRLINE_VX,AIRLINE_WN,ORIGIN_WOE_30,DESTINATION_WOE_30,DAY_OF_YEAR_WOE_30
0,464.0,669.0,0,0,0,0,0,0,0,0,0,1,0,0,0,-0.177348,-0.003495,-0.586823
1,596.0,742.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0.166972,0.082505,0.258996
2,452.0,575.0,0,0,1,0,0,0,0,0,0,0,0,0,0,-0.176318,0.133607,-0.778808
3,895.0,1050.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0.066534,-0.250770,-0.042656
4,449.0,960.0,0,0,1,0,0,0,0,0,0,0,0,0,0,-0.943535,0.133607,0.388327

(382693, 18)

In [ ]:
sc = StandardScaler()
X_test_trans = sc.fit_transform(X_test)
X_train_trans = sc.fit_transform(X_train)

In [ ]:
SVM = svm.SVC(kernel='rbf')
SVM.fit(X_train, y_train)

In [ ]:
y_pred = SVM.predict(X_test)

In [ ]:
accuracy_score(y_pred, y_test)